//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.TCP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TCP.ICompilerService")]
    public interface ICompilerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileCPP", ReplyAction="http://tempuri.org/ICompilerService/CompileCPPResponse")]
        string CompileCPP(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileCPP", ReplyAction="http://tempuri.org/ICompilerService/CompileCPPResponse")]
        System.Threading.Tasks.Task<string> CompileCPPAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileCPPWithInput", ReplyAction="http://tempuri.org/ICompilerService/CompileCPPWithInputResponse")]
        string CompileCPPWithInput(string code, string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileCPPWithInput", ReplyAction="http://tempuri.org/ICompilerService/CompileCPPWithInputResponse")]
        System.Threading.Tasks.Task<string> CompileCPPWithInputAsync(string code, string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileC", ReplyAction="http://tempuri.org/ICompilerService/CompileCResponse")]
        string CompileC(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileC", ReplyAction="http://tempuri.org/ICompilerService/CompileCResponse")]
        System.Threading.Tasks.Task<string> CompileCAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileCWithInput", ReplyAction="http://tempuri.org/ICompilerService/CompileCWithInputResponse")]
        string CompileCWithInput(string code, string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileCWithInput", ReplyAction="http://tempuri.org/ICompilerService/CompileCWithInputResponse")]
        System.Threading.Tasks.Task<string> CompileCWithInputAsync(string code, string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompilePython", ReplyAction="http://tempuri.org/ICompilerService/CompilePythonResponse")]
        string CompilePython(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompilePython", ReplyAction="http://tempuri.org/ICompilerService/CompilePythonResponse")]
        System.Threading.Tasks.Task<string> CompilePythonAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompilePythonWithInput", ReplyAction="http://tempuri.org/ICompilerService/CompilePythonWithInputResponse")]
        string CompilePythonWithInput(string code, string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompilePythonWithInput", ReplyAction="http://tempuri.org/ICompilerService/CompilePythonWithInputResponse")]
        System.Threading.Tasks.Task<string> CompilePythonWithInputAsync(string code, string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileJava", ReplyAction="http://tempuri.org/ICompilerService/CompileJavaResponse")]
        string CompileJava(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileJava", ReplyAction="http://tempuri.org/ICompilerService/CompileJavaResponse")]
        System.Threading.Tasks.Task<string> CompileJavaAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileJavaWithInput", ReplyAction="http://tempuri.org/ICompilerService/CompileJavaWithInputResponse")]
        string CompileJavaWithInput(string code, string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompilerService/CompileJavaWithInput", ReplyAction="http://tempuri.org/ICompilerService/CompileJavaWithInputResponse")]
        System.Threading.Tasks.Task<string> CompileJavaWithInputAsync(string code, string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompilerServiceChannel : Client.TCP.ICompilerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompilerServiceClient : System.ServiceModel.ClientBase<Client.TCP.ICompilerService>, Client.TCP.ICompilerService {
        
        public CompilerServiceClient() {
        }
        
        public CompilerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompilerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompilerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompilerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CompileCPP(string value) {
            return base.Channel.CompileCPP(value);
        }
        
        public System.Threading.Tasks.Task<string> CompileCPPAsync(string value) {
            return base.Channel.CompileCPPAsync(value);
        }
        
        public string CompileCPPWithInput(string code, string input) {
            return base.Channel.CompileCPPWithInput(code, input);
        }
        
        public System.Threading.Tasks.Task<string> CompileCPPWithInputAsync(string code, string input) {
            return base.Channel.CompileCPPWithInputAsync(code, input);
        }
        
        public string CompileC(string value) {
            return base.Channel.CompileC(value);
        }
        
        public System.Threading.Tasks.Task<string> CompileCAsync(string value) {
            return base.Channel.CompileCAsync(value);
        }
        
        public string CompileCWithInput(string code, string input) {
            return base.Channel.CompileCWithInput(code, input);
        }
        
        public System.Threading.Tasks.Task<string> CompileCWithInputAsync(string code, string input) {
            return base.Channel.CompileCWithInputAsync(code, input);
        }
        
        public string CompilePython(string value) {
            return base.Channel.CompilePython(value);
        }
        
        public System.Threading.Tasks.Task<string> CompilePythonAsync(string value) {
            return base.Channel.CompilePythonAsync(value);
        }
        
        public string CompilePythonWithInput(string code, string input) {
            return base.Channel.CompilePythonWithInput(code, input);
        }
        
        public System.Threading.Tasks.Task<string> CompilePythonWithInputAsync(string code, string input) {
            return base.Channel.CompilePythonWithInputAsync(code, input);
        }
        
        public string CompileJava(string value) {
            return base.Channel.CompileJava(value);
        }
        
        public System.Threading.Tasks.Task<string> CompileJavaAsync(string value) {
            return base.Channel.CompileJavaAsync(value);
        }
        
        public string CompileJavaWithInput(string code, string input) {
            return base.Channel.CompileJavaWithInput(code, input);
        }
        
        public System.Threading.Tasks.Task<string> CompileJavaWithInputAsync(string code, string input) {
            return base.Channel.CompileJavaWithInputAsync(code, input);
        }
    }
}
